# ─── Databricks App: Actuarial Risk Dashboard ────────────────────────────────
# Streamlit application served via Databricks Apps (serverless, UC-integrated).
# Runtime configuration (env vars, command) lives in app/app.yaml and has
# bundle variables substituted at deploy time.

resources:
  apps:
    actuarial_workshop_app:
      name: "actuarial-workshop"
      source_code_path: ../app

      # ── CATALOG / SCHEMA / PGDATABASE ────────────────────────────────────────
      # Provided to the app via app/_bundle_config.py, which deploy.sh generates
      # with the resolved variable values before each deploy. See deploy.sh.

      # ── App resource authorizations ──────────────────────────────────────────
      # Each entry grants the app's service principal a specific permission on a
      # Databricks resource. Values are injected into the app at runtime via
      # valueFrom in app/app.yaml — no credentials are embedded in source code.
      resources:
        - name: sql-warehouse
          description: "SQL Warehouse for Statement Execution API (claims data queries)"
          sql_warehouse:
            id: "${var.warehouse_id}"
            permission: CAN_USE

        # Lakebase Autoscaling projects do not support the 'database' app resource
        # type — there is no valueFrom injection for postgres_projects. The app
        # resolves PGHOST at runtime via the SDK and authenticates via
        # generate_database_credential. Permissions are granted in app_setup.py.
