# ─── DLT Pipeline: Medallion Architecture ────────────────────────────────────
# Three connected medallion pipelines:
#   A) Reserve CDC:  reserve_development_raw → bronze_reserve_cdc → silver_reserves → gold_reserve_triangle
#   B) Claims:       claims_events_raw → bronze_claims → gold_claims_monthly
#   C) Macro:        macro_indicators_raw → bronze_macro → silver_macro → gold_macro_features
# Source notebook: src/01_dlt_pipeline_and_jobs.py

resources:
  pipelines:
    actuarial_workshop_dlt:
      name: "actuarial-workshop-medallion"
      # Unity Catalog target — tables are created in ${var.catalog}.${var.schema}
      catalog: "${var.catalog}"
      target: "${var.schema}"

      # Serverless preferred; falls back gracefully to classic compute
      serverless: true
      channel: CURRENT
      continuous: false

      # These key-value pairs are accessible in the notebook via spark.conf.get()
      configuration:
        catalog: "${var.catalog}"
        schema: "${var.schema}"
        notification_email: "${var.notification_email}"

      libraries:
        - notebook:
            path: ../src/01_dlt_pipeline_and_jobs.py
