# app.yaml — Databricks App configuration for Actuarial Workshop
#
# DEPLOYMENT OPTIONS
# ──────────────────
# 1. Via Databricks Asset Bundle (recommended):
#      databricks bundle deploy --target <target>
#    Bundle variables (${var.*}) are substituted from databricks.yml at deploy time.
#
# 2. Direct CLI deployment (standalone):
#      databricks apps deploy actuarial-workshop --source-code-path ./app
#    Replace ${var.*} placeholders with actual values before deploying.
#
# 3. Local development:
#      export DATABRICKS_HOST=https://...  CATALOG=...  SCHEMA=...  etc.
#      streamlit run app.py

command:
  - "streamlit"
  - "run"
  - "app.py"
  - "--server.port=8000"
  - "--server.address=0.0.0.0"

env:
  # Streamlit
  - name: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
    value: "false"

  # DATABRICKS_HOST is injected automatically by the Databricks Apps runtime.
  # Do NOT set it here — ${workspace.host} is a bundle-level reference that is
  # not substituted in app.yaml, which causes the literal string to be used.

  # Data layer — set in databricks.yml variables
  - name: CATALOG
    value: "${var.catalog}"
  - name: SCHEMA
    value: "${var.schema}"

  # Model serving — injected at runtime from the 'serving-endpoint' app resource.
  # The app's service principal is granted CAN_QUERY on the endpoint (see app.yml).
  - name: ENDPOINT_NAME
    valueFrom: serving-endpoint

  # SQL execution — injected at runtime from the 'sql-warehouse' app resource.
  # The app's service principal is granted CAN_USE on the warehouse (see app.yml).
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse

  # Lakebase (Postgres) — PGHOST injected at runtime from the 'database' app resource.
  # The app's service principal is granted CAN_CONNECT_AND_CREATE (see app.yml).
  # PGHOST is empty → Lakebase features are gracefully disabled if resource is absent.
  - name: PGHOST
    valueFrom: database
  - name: PGPORT
    value: "5432"
  - name: PGDATABASE
    value: "${var.pg_database}"
  - name: PGSSLMODE
    value: "require"
