import os

# CATALOG / SCHEMA / PG_DATABASE / ENDPOINT_NAME / LAKEBASE_ENDPOINT_PATH come
# from app/_bundle_config.py, generated by deploy.sh before each deploy.
try:
    import _bundle_config as _bc
except ImportError:
    _bc = None


def _cfg(attr, default):
    """Read from _bundle_config if available, otherwise use default."""
    if _bc is not None:
        return getattr(_bc, attr, default)
    return default


WORKSPACE_HOST = os.environ.get("DATABRICKS_HOST", "")
if WORKSPACE_HOST and not WORKSPACE_HOST.startswith("http"):
    WORKSPACE_HOST = f"https://{WORKSPACE_HOST}"

WAREHOUSE_ID           = os.environ.get("DATABRICKS_WAREHOUSE_ID", "")
CATALOG                = os.environ.get("CATALOG") or _cfg("CATALOG", "my_catalog")
SCHEMA                 = os.environ.get("SCHEMA") or _cfg("SCHEMA", "actuarial_workshop")
PG_DATABASE_DEFAULT    = _cfg("PG_DATABASE", "actuarial_workshop_db")
ENDPOINT_NAME          = os.environ.get("ENDPOINT_NAME") or _cfg("ENDPOINT_NAME", "actuarial-workshop-sarima-forecaster")
MC_ENDPOINT_NAME       = os.environ.get("MC_ENDPOINT_NAME") or _cfg("MC_ENDPOINT_NAME", "actuarial-workshop-monte-carlo")
LAKEBASE_ENDPOINT_PATH = os.environ.get("LAKEBASE_ENDPOINT_PATH") or _cfg("LAKEBASE_ENDPOINT_PATH", "projects/actuarial-workshop-lakebase/branches/main/endpoints/primary")
LLM_ENDPOINT_NAME      = os.environ.get("LLM_ENDPOINT_NAME") or _cfg("LLM_ENDPOINT_NAME", "databricks-meta-llama-3-3-70b-instruct")
GENIE_SPACE_ID         = os.environ.get("GENIE_SPACE_ID") or _cfg("GENIE_SPACE_ID", "")
LAKEBASE_HOST          = _cfg("LAKEBASE_HOST", "")
