import os

# CATALOG / SCHEMA / PG_DATABASE / ENDPOINT_NAME / LAKEBASE_ENDPOINT_PATH come
# from app/_bundle_config.py, generated by deploy.sh before each deploy.
try:
    from _bundle_config import (
        CATALOG as _BC_CATALOG,
        SCHEMA as _BC_SCHEMA,
        PG_DATABASE as _BC_PG,
        ENDPOINT_NAME as _BC_ENDPOINT,
        LAKEBASE_ENDPOINT_PATH as _BC_LAKEBASE_PATH,
        LAKEBASE_HOST as _BC_LAKEBASE_HOST,
    )
    try:
        from _bundle_config import MC_ENDPOINT_NAME as _BC_MC_ENDPOINT
    except ImportError:
        _BC_MC_ENDPOINT = "actuarial-workshop-monte-carlo"
except ImportError:
    _BC_CATALOG = "my_catalog"
    _BC_SCHEMA = "actuarial_workshop"
    _BC_PG = "actuarial_workshop_db"
    _BC_ENDPOINT = "actuarial-workshop-sarima-forecaster"
    _BC_MC_ENDPOINT = "actuarial-workshop-monte-carlo"
    _BC_LAKEBASE_PATH = "projects/actuarial-workshop-lakebase/branches/main/endpoints/primary"
    _BC_LAKEBASE_HOST = ""

WORKSPACE_HOST = os.environ.get("DATABRICKS_HOST", "")
if WORKSPACE_HOST and not WORKSPACE_HOST.startswith("http"):
    WORKSPACE_HOST = f"https://{WORKSPACE_HOST}"

WAREHOUSE_ID           = os.environ.get("DATABRICKS_WAREHOUSE_ID", "")
CATALOG                = os.environ.get("CATALOG") or _BC_CATALOG
SCHEMA                 = os.environ.get("SCHEMA") or _BC_SCHEMA
PG_DATABASE_DEFAULT    = _BC_PG
ENDPOINT_NAME          = os.environ.get("ENDPOINT_NAME") or _BC_ENDPOINT
MC_ENDPOINT_NAME       = os.environ.get("MC_ENDPOINT_NAME") or _BC_MC_ENDPOINT
LAKEBASE_ENDPOINT_PATH = os.environ.get("LAKEBASE_ENDPOINT_PATH") or _BC_LAKEBASE_PATH

# Chatbot LLM endpoint (Foundation Model API via AI Gateway)
LLM_ENDPOINT_NAME      = os.environ.get("LLM_ENDPOINT_NAME", "databricks-meta-llama-3-3-70b-instruct")
