"""
gen_bundle_config.py — called by bundle.scripts.preDeploy in databricks.yml

Generates app/_bundle_config.py with the bundle variable values substituted
at deploy time. The bundle substitutes ${var.*} references in the command
string before invoking this script, so sys.argv[1:4] contain the real values.

Usage (called by bundle, not directly):
    python scripts/gen_bundle_config.py <catalog> <schema> <pg_database>
"""
import sys
import pathlib

if len(sys.argv) < 4:
    print("Usage: gen_bundle_config.py <catalog> <schema> <pg_database>", file=sys.stderr)
    sys.exit(1)

catalog, schema, pg_database = sys.argv[1], sys.argv[2], sys.argv[3]

out = pathlib.Path(__file__).parent.parent / "app" / "_bundle_config.py"
out.write_text(
    f"# Auto-generated by DAB preDeploy — do not edit or commit\n"
    f"CATALOG = {catalog!r}\n"
    f"SCHEMA = {schema!r}\n"
    f"PG_DATABASE = {pg_database!r}\n"
)
print(f"[gen_bundle_config] wrote {out}: CATALOG={catalog!r}, SCHEMA={schema!r}, PG_DATABASE={pg_database!r}")
