"""
gen_bundle_config.py — called by deploy.sh before each bundle deploy.

Writes app/_bundle_config.py with the resolved catalog, schema, and
pg_database values so the app can import them at startup.

Usage:
    python scripts/gen_bundle_config.py <catalog> <schema> <pg_database>
"""
import sys
import pathlib

if len(sys.argv) < 4:
    print("Usage: gen_bundle_config.py <catalog> <schema> <pg_database>", file=sys.stderr)
    sys.exit(1)

catalog, schema, pg_database = sys.argv[1], sys.argv[2], sys.argv[3]

out = pathlib.Path(__file__).parent.parent / "app" / "_bundle_config.py"
out.write_text(
    f"# Auto-generated by DAB preDeploy — do not edit or commit\n"
    f"CATALOG = {catalog!r}\n"
    f"SCHEMA = {schema!r}\n"
    f"PG_DATABASE = {pg_database!r}\n"
)
print(f"[gen_bundle_config] wrote {out}: CATALOG={catalog!r}, SCHEMA={schema!r}, PG_DATABASE={pg_database!r}")
